title: Website Design Examples
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3910542668309063
  brandStrength: 0.5625
  rhythmicContrast: 0.7252523514907807
  brandColors:
    - '#0374bb'
    - '#2bb24d'
    - '#000000'
    - '#404040'
    - '#84bbde'
  lightness: 0.0988544246647507
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Website Design
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.75787
layout_spectrum: 0.8458647
